### This file contains anwers Task 4.8

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# create path
path = r'/Users/macbook/Library/CloudStorage/OneDrive-Personal/Data Analisys/Instacart/02 Data'

In [3]:
ords_prods_merge = pd.read_pickle(os.path.join(path, 'Prepared Data', 'orders_products_merged_update.pkl'))

In [4]:
# Subset DataFrame
df = ords_prods_merge[:1000000]

In [5]:
df.shape

(1000000, 19)

In [6]:
df.head(5)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders

#### In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [7]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

#### Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code

In [8]:
# Comparing to subset
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

Compared to subset, the entire dataframe gives entire picture of order number from all departments. In other words, picture of POPULATION vs. SAMPLE. The range of 'order_number' mean is also larger (DATA SPREAD)

#### Creating a loyalty flag for existing customers using the transform() and loc() functions

In [9]:
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [10]:
pd.options.display.max_rows = None

In [11]:
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Average orders,10
6,550135,1,prior,7,1,9,20.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
14,487368,15,prior,22,1,10,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
15,2293453,19,prior,2,5,14,6.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,9
16,1973799,19,prior,5,6,12,8.0,196,15,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,9
17,532817,19,prior,7,4,17,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,9
18,1573906,21,prior,10,3,10,6.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,33
19,1593000,31,prior,10,3,8,7.0,196,17,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
20,2231262,31,prior,17,3,11,8.0,196,14,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,20
21,2580647,43,prior,6,4,16,4.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
22,2187180,43,prior,9,4,12,3.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,11
23,2497897,52,prior,1,1,9,NaN,196,4,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
24,1318871,52,prior,2,1,10,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
25,1261384,52,prior,3,1,10,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
26,580568,52,prior,5,2,10,8.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
27,2428073,52,prior,7,2,7,8.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Average orders,27
28,342306,52,prior,9,1,11,7.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
29,1520353,52,prior,10,2,10,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
30,2542086,52,prior,11,2,9,7.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
31,944694,52,prior,12,1,16,6.0,196,7,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,27
32,1268191,52,prior,15,2,11,8.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
33,1122089,52,prior,17,2,10,6.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
34,1498922,52,prior,18,2,10,14.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
35,180919,52,prior,19,3,8,8.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,27
36,2695875,52,prior,21,5,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,27
37,3205960,67,prior,1,3,11,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
38,970922,67,prior,2,1,15,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
39,596585,67,prior,3,1,13,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
40,2037087,67,prior,4,2,9,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,24
41,2474111,67,prior,5,3,14,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
42,1568481,67,prior,6,3,12,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,24
43,2048527,67,prior,8,2,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,24
44,2389031,67,prior,9,2,14,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,24
45,2378562,67,prior,10,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
46,1515698,67,prior,11,1,11,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
47,1928050,67,prior,12,2,12,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,24
48,1949274,67,prior,13,1,10,6.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
49,551869,67,prior,14,1,9,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
50,768572,67,prior,16,4,10,9.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,24
51,150528,67,prior,18,5,16,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,24
52,29758,67,prior,19,0,14,9.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,24
53,1558976,67,prior,21,1,9,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
54,863974,67,prior,22,1,11,14.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
55,2308399,67,prior,23,1,14,14.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,24
56,2759128,81,prior,3,1,9,14.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,7
57,1812985,81,prior,5,2,20,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Average orders,7
58,1889835,82,prior,1,3,15,NaN,196,6,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,19
59,499460,82,prior,3,5,10,5.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,19
60,2728456,82,prior,4,0,11,16.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,19
61,2653743,82,prior,6,4,9,13.0,196,5,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,19
62,1358880,82,prior,9,1,10,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
63,343588,82,prior,10,2,11,1.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,19
64,3034663,82,prior,15,2,11,12.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,19
65,147262,82,prior,18,1,13,7.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,19
66,3144004,82,prior,19,2,15,8.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,19
67,2126069,98,prior,3,0,9,25.0,196,7,0,Soda,77,7,9.0,both,Mid-range product,Busiest day,Busiest days,Most orders,14
68,2210120,98,prior,7,5,14,5.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,14
69,681011,98,prior,9,3,9,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,14
70,2846344,98,prior,11,4,13,15.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
71,747431,98,prior,12,6,13,30.0,196,4,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,14
72,2383054,98,prior,13,4,11,30.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,14
73,1993729,98,prior,14,5,8,8.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,14
74,1403849,109,prior,3,3,17,9.0,196,5,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,6
75,520620,120,prior,1,3,11,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
76,3273029,120,prior,3,2,8,19.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,3
77,1861943,185,prior,2,1,12,25.0,196,10,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,6
78,2040988,195,prior,1,1,14,NaN,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
79,1680569,195,prior,8,1,9,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
80,276171,195,prior,19,5,11,3.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,58
81,2744976,195,prior,22,5,10,7.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,58
82,2781919,195,prior,25,1,14,4.0,196,1,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,58
83,1738718,195,prior,31,2,8,4.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,58
84,3058369,195,prior,34,3,10,6.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
85,1485596,195,prior,37,2,15,0.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,58
86,417035,195,prior,40,3,16,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
87,1615297,195,prior,47,5,10,2.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,58
88,1765587,195,prior,52,3,12,2.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,58
89,745908,195,prior,57,4,11,3.0,196,3,1,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,58
90,2505656,222,prior,17,2,12,1.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,70
91,3268370,222,prior,38,5,15,1.0,196,6,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,70
92,2016711,290,prior,9,5,19,6.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,51
93,2706088,290,prior,28,6,10,7.0,196,16,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,51
94,1952286,331,prior,6,5,16,30.0,196,8,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,8
95,3226575,360,prior,1,5,12,NaN,196,1,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,8
98,858092,420,prior,4,1,19,30.0,196,2,0,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,22
99,119314,420,prior,5,3,19,16.0,196,2,1,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,22

Creating a flag that assigns a “loyalty” label to a customer_id based on its corresponding max order value

#### Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [12]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [13]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [14]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [15]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [16]:
ords_prods_merge.shape

(32404859, 21)

In [17]:
ords_prods_merge.head(5)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,77,7,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,10,New customer
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer
2,473747,1,prior,3,3,12,21.0,196,1,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer
4,431534,1,prior,5,4,15,28.0,196,1,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer

#### The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:
If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [18]:
# Create new column 'avg_price'
ords_prods_merge['avg_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [19]:
# Create a flag that assigns a “types of spenders” label to a user ID based on average prices.
ords_prods_merge.loc[ords_prods_merge['avg_price'] < 10, 'spender_flag'] = 'Low spender'

In [20]:
ords_prods_merge.loc[ords_prods_merge['avg_price'] >= 10, 'spender_flag'] = 'High spender'

In [21]:
ords_prods_merge['spender_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spender_flag, dtype: int64

In [22]:
ords_prods_merge.head(5)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,avg_price,spender_flag
0,2539329,1,prior,1,2,8,NaN,196,1,0,...,9.0,both,Mid-range product,Regularly busy,Regulary busy days,Most orders,10,New customer,6.367797,Low spender
1,2398795,1,prior,2,3,7,15.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,6.367797,Low spender
2,473747,1,prior,3,3,12,21.0,196,1,1,...,9.0,both,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,6.367797,Low spender
3,2254736,1,prior,4,4,7,29.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,6.367797,Low spender
4,431534,1,prior,5,4,15,28.0,196,1,1,...,9.0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,6.367797,Low spender

#### The Instacart team wants to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”

In [28]:
ords_prods_merge['median_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [30]:
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order']>20, 'frequency_flag'] = 'Non-frequent customer'

In [31]:
ords_prods_merge.loc[(ords_prods_merge['median_days_since_prior_order']>10) & (ords_prods_merge['median_days_since_prior_order']<=20), 'frequency_flag'] = 'Regular customer'

In [32]:
ords_prods_merge.loc[ords_prods_merge['median_days_since_prior_order']<=10, 'frequency_flag'] = 'Frequent customer'

In [33]:
ords_prods_merge['frequency_flag'].value_counts(dropna = False)

Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: frequency_flag, dtype: int64

In [35]:
ords_prods_merge.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name', 'aisle_id',
       'department_id', 'prices', '_merge', 'price_range_loc', 'busiest_day',
       'busiest_days', 'busiest_period_of_day', 'max_order', 'loyalty_flag',
       'avg_price', 'spender_flag', 'median_days_since_prior_order',
       'frequency_flag'],
      dtype='object')

#### Export your dataframe as a pickle file and store it correctly in your “Prepared Data” folder.

In [ ]:
# Export to PKL
ords_prods_merge.to_pickle(os.path.join(path,'Prepared Data', 'orders_products_merged_update2.pkl'))